### ISSUE TITLE
scanpy-scripts related warnings when scanpy is updated

### ISSUE THREAD

**Issue by mathog** [ebi-gene-expression-group/scanpy-scripts#80] opened 2020-06-10 18:55 UTC
My system keeps all versions of packages in PYTHONPATH (python3)
and a command like this:

pip3 install scanpy   --target $PYTHONPATH --upgrade

has among its many other messages these scanpy-scripts related errors:

```
ERROR: scanpy-scripts 0.2.10 has requirement anndata<0.6.20, but you'll have anndata 0.7.3 which is incompatible.
ERROR: scanpy-scripts 0.2.10 has requirement h5py<2.10, but you'll have h5py 2.10.0 which is incompatible.
ERROR: scanpy-scripts 0.2.10 has requirement loompy<3.0.0,>=2.0.0, but you'll have loompy 3.0.6 which is incompatible.
ERROR: scanpy-scripts 0.2.10 has requirement scanpy<1.4.4,>=1.4.2, but you'll have scanpy 1.5.1 which is incompatible.
ERROR: scanpy-scripts 0.2.10 has requirement scipy<1.3.0,>=1.2.0, but you'll have scipy 1.4.1 which is incompatible.
```

The thing is, versions in the correct range exist for all of those.  Example:

```
ls -1 $PYTHONPATH | grep scipy
scipy
scipy-1.2.3.dist-info
scipy-1.2.3-py3.6-linux-x86_64.egg
scipy-1.4.1.dist-info
```
This is probably irrelevant, but the machine has Python 3.6.8 on CentOS 8.1.1911.

**Comment by nh3** [comment] 2020-06-11 07:56
The issue here is caused by pip attempting to install the latest version of scanpy and its dependencies, which are not supported by scanpy-scripts. The version it quotes, e.g. `scipy 1.4.1` is the version it *will* install rather than the version installed already.

**Comment by pcm32** [comment] 2020-06-11 08:45
You should probably aim to use scanpy-scripts on it's own virtualenv @mathog. Then you can have the base installation or other envs with other versions of the above software for other needs that you might have. Installing everything on the base python installation is a recipe for disaster when it comes to conflicting dependencies between packages, I would suggest that you follow the rule one tool -> one virtualenv (or in conda with envs, as we do it).

**Comment by mathog** [comment] 2020-06-11 19:52
Will scanpy-scripts be updated at some point to use the current version of scanpy?

I am not a fan of virtualenv's since it results in numerous copies of the same package being installed.  Admittedly Python is way down on my list of languages, but is not the common usage of virtualenv to avoid version conflicts the result of python packages which use this:

```
import FussyPkg
```

when they should use this:

```
__requires__ = [' FussyPkg >1.5,<=2.0,!=1.7']
import pkg_resources
import FussyPkg
```
when they have known version requirements?

(Imagine what linux or Windows would look like if they could not keep multiple versions of dynamic link libraries in the same directory,)

In the present case this seems to work to load the desired versions from the common PYTHONPATH:
```
python3
__requires__ = ['scipy <1.3.0,>=1.2.0', 'anndata <0.6.20', 'loompy <3.0.0.>=2.00', 'h5py <2.10']
import pkg_resources
import scipy
print(scipy.__version__)
import anndata
print(anndata.__version__)
import loompy
print(loompy.__version__)
import h5py
print(h5py.__version__)
import scanpy
print(scanpy.__version__)
quit()

#emits:
Python 3.6.8 (default, Nov 21 2019, 19:31:34) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> __requires__ = ['scipy <1.3.0,>=1.2.0', 'anndata <0.6.20', 'loompy <3.0.0.>=2.00', 'h5py <2.10']
>>> import pkg_resources
>>> import scipy
>>> print(scipy.__version__)
1.2.3
>>> import anndata
/home/common/lib/python3.6/site-packages/anndata-0.6.19-py3.6.egg/anndata/base.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
>>> print(anndata.__version__)
0.6.19
>>> import loompy
>>> print(loompy.__version__)
2.0.17
>>> import h5py
>>> print(h5py.__version__)
2.9.0
>>> import scanpy
>>> print(scanpy.__version__)
1.4.3
>>> quit()
```

However, note that there was no scanpy on the requires line.  If one adds at the end of the list in  __requires__:

`, 'scanpy <1.4.4,>=1.4.2'
`

it breaks the whole thing.

```
python3
Python 3.6.8 (default, Nov 21 2019, 19:31:34) 
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> __requires__ = ['scipy <1.3.0,>=1.2.0', 'anndata <0.6.20', 'loompy <3.0.0.>=2.00', 'h5py <2.10', 'scanpy <1.4.4,>=1.4.2']
>>> import pkg_resources
Traceback (most recent call last):
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/common/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (scanpy 1.5.1 (/home/common/lib/python3.6/site-packages), Requirement.parse('scanpy<1.4.4,>=1.4.2'))
#and other problems...

```

That list bit really confuses me so I asked on stackoverflow for an explanation.

**Comment by nh3** [comment] 2020-06-11 20:12
We just started working on supporting scanpy 1.5.x, but it will not happen overnight or even overweek.

If you install scanpy with `pip3 install scanpy==1.4.3`, your last bit of error would possibly go away.

But, your method of selecting package version is not reliable. No package developer afaik write imports like that, so you won't have control over all imported packages down the dependency graph. I'd really suggest you look into conda. Conda makes links rather than copies of the same file as much as possible, so it doesn't necessarily waste your disk space while providing multiple isolated environment. And you can still use pip alongside conda if required. Just my two cents.

**Comment by pcm32** [comment] 2020-06-11 20:35
> I am not a fan of virtualenv's since it results in numerous copies of the same package being installed.

I wonder how this could be relevant when developer time is so much more expensive than disk space. A few GBs against hours and hours of resolving version conflicts?

Out of interest I just made the exercise of counting my venvs and sizes (it had never crossed my mind even to worry about this), around 40 venvs or so... they all use like 6 GBs of disk.. compared to the time they save me in resolving irrelevant version conflicts, I think it is negligible.

**Comment by pcm32** [comment] 2020-06-11 20:39
I'm going to close this since this is not an issue/bug of the cli layer, as supported versions are clearly labeled [here](https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/develop/setup.py#L44).

**Closed by pcm32** 2020-06-11 20:39 UTC
